### PR TITLE
Remove some duplicate imports and (mostly) tidy up to PEP8.

### PR DESCRIPTION
**Pull request by StevenMaude**
Again, think all is well, but would be good for someone else to check over before deploying!

### CODE REVIEW

**Comment by frabcus** [comment]
Bother, thought I had merged this and hadn't!

It needs rebasing...

**Comment by StevenMaude** [comment]
Updated and looks good to me; can someone check this please?

**Comment by pwaller** [comment]
I'm confused. Github says it was merged - is this true? It doesn't seem if if I understand correctly. I can only guess this is what a force against master looks like?

**Comment by StevenMaude** [comment]
No, this is my mistake and I should be slapped on the wrists accordingly.

While fixing this, I just figured it was as easy to redo the fixes as deal with the merge conflicts. This time, I managed to add the commit to master instead (don't ask). I then figured I'd just checkout a new branch and push the branch.

While on the branch, I accidentally pushed to _all_ branches with `push -u origin`, rather than just the branch I was on (no force necessary as the new commit was based on `master`). I then went back to the previous commit on master and forced a push. So, this commit wasn't actually merged via this pull request, but the commit was added directly to master.

In retrospect, the better thing to do was probably leave it intact in retrospect, especially as I don't think there are any issues with the commit.

Other lessons: keep things tidy before doing any pushing and don't forget to `push origin HEAD`.

**Comment by pwaller** [comment]
No worries! Just trying to make sense of what happened. Easily done :)

For the record, in general the less evil approach than forcing master is to use "git revert" to make a new commit which undoes the old one. On the other hand, it's fine in this case since there are so few of us working on it and pulling on it, what you did was probably fine. You can get unlucky though :)

**Comment by StevenMaude** [comment]
Noted; thanks for the tip!

**Pull request merged**
